# Generated by Django 4.1.7 on 2023-03-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_desc',
            field=models.TextField(default=models.CharField(max_length=200), max_length=1000),
        ),
    ]
