# Generated by Django 4.1.7 on 2023-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
