# Generated by Django 4.1.7 on 2023-03-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='like_count',
        ),
    ]
